version: '3.0'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongodb:27017/taskify
    networks:
      - app-network
    image: gaurav1954/taskify
networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
